### ISSUE TITLE
logo and keywords

### ISSUE THREAD

**Issue by vitaly-t** [promises-aplus/promises-spec#184]
In your documents you mention that a compliant Promises/A+ library may display a logo and use a keyword on NPM.

And what about libraries that feature use of Promises/A+, i.e. libraries that expose its interface via any of the existing Promises/A+ implementations?

Any similar provision for such libraries? May/should they use the same keyword on NPM? May/should they use the same logo?

**Comment by briancavalier** [comment]
Hey @vitaly-t.  Personally, I think it's perfectly fine, and even encouraged, to add the logo and keywords to a README or documentation.  As long as its clear, from the README for example, that the project accepts/returns promises, rather than being a Promises/A+ implementation.

Here's an example.  In another project, I [added a section](https://github.com/cujojs/most#iteroperability) to list specs it interoperates with.  It also lists keywords in its [package.json](https://github.com/cujojs/most/blob/master/package.json#L20-L22) and [bower.json](https://github.com/cujojs/most/blob/master/bower.json#L20-L22).

**Comment by vitaly-t** [comment]
Thanks. I wasn't asking for a hypothetical reason, I did a library that can switch between various Promises/A+ implementations: https://github.com/vitaly-t/pg-promise

And I made a join logo of the two technologies being featured. I hope this doesn't violate any policy around use of Promises/A+ logo :)

Thank you for your answer.
