### ISSUE TITLE
Example for abstract definition: "promise resolution procedure"

### ISSUE THREAD

**Issue by MalteFabian** [promises-aplus/promises-spec#214]
Hi,
I don't quite get the meaning of this sentence:
> The promise resolution procedure is an abstract operation taking as input a promise and a value, which we denote as [...].

Can this mean something like (*Pseudocode*):
```
function(promise, x) {
   if (promise === x) {
      throw new TypeError();
   }  
   // do more stuff
}
```
If this is the case, does this function has anything to do with resolving a promise? To be more precise: what is the meaning of *resolution*?

**Comment by bergus** [comment]
Have a look at http://stackoverflow.com/questions/29268569/what-is-the-correct-terminology-for-javascript-promises
Yes, *resolution* is exactly the substantive for *resolving*.

**Comment by MalteFabian** [comment]
Alright, thanks. I mainly was confused because of two points, both regarding the use of Promises in the AngularJS/$q context.

* $q.defer().resolve should actually be called $q.defer().fulfill. Am I right with this assumption?
* I've never seen an API like this: PromiseObject.resolve(promise, value). The [Promise[Object].resolve method section](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-resolve-functions) of ECMAScript 2015 actually states, that `promise` is an internal slot of the PromiseObject.

But anyway, angular.$q might not follow the spec (**this spec**), then it is not a good example.

**Comment by ForbesLindesay** [comment]
The promise resolution procedure is an **abstract** operation.  What this means is that it is a description of some functionality for use within the spec, rather than a function or method that should actually be exposed to users.  Some promise implementations do have a function very similar to this one, many do not.

 - `$q.defer().resolve` should internally run the promise resolution procedure with the promise attached to `$q.defer()` and the argument you pass to `$q.defer().resolve`.
 - As I said, libraries don't expose the promise resolution procedure as a public method, but rather use it internally as an implementation detail.

**Comment by bergus** [comment]
> `$q.defer().resolve` should actually be called `$q.defer().fulfill`. Am I right with this assumption?

No. `resolve` does not necessarily fulfill the promise. You can resolve with a rejected promise, leading to a rejection, or you can resolve with a never-settling promise, leading to nothing but the lock-in.

**Comment by MalteFabian** [comment]
Many thanks for the background stuff.
