### ISSUE TITLE
Incorporate monads and category theory

### ISSUE THREAD

**Issue by paulmillr** [promises-aplus/promises-spec#94]
Brian Mckenna criticised current spec. He proposes to use FP approach to achieve much better modularity.

Suggest to read it, really good ideas with just three changes.

http://brianmckenna.org/blog/category_theory_promisesaplus

His proposal is to incorporate into spec three simple apis:
1. `Promise.of(a)` will turn anything into promise.
2. `Promise#then(f)` should take one function, not two.
3. `Promise#onRejected(f)`: move `onRejected` to prototype instead of second arg.

**edit:** see https://github.com/promises-aplus/resolvers-spec/issues/24 for more discussion

**Comment by AriaFallah** [comment]
Well that was informative :smile: thanks @puffnfresh

**Comment by donhatch** [comment]
In @domenic 's April 11 2013 comment, ey said "it has previously been discussed over and over that a promise-for-a-thenable is a problematic pattern in JavaScript and should not be supported".

Can someone provide some links to such discussions?
At this moment I have no idea why anyone thinks special-casing thenables is a good thing.

**Comment by donhatch** [comment]
In answer to my Oct 21 question, I found these:
- [Arguments in favor of Promises for Promises](https://gist.github.com/ForbesLindesay/5392701)
- [Arguments against Promises for Promises](https://gist.github.com/ForbesLindesay/5392612)

and some great discussion threads linked from comments on the latter (in particular, from the two Apr 25, 2013 comments).

**Comment by John322** [comment]
Every day begins with big challenges at your college or university. These can be preparing a speech or writing an essay. It seems simple enough. But when you start working, you sometimes realize you have no idea where to begin. Sometimes, your mind just goes blank. If this is you, then a website like www.123helpme.com will be very helpful. If you seek information about “<a href="">invite code for 123helpme</a>”, welcome to Scamfighter.

**Comment by ghost** [comment]
Fucking Haskell-tards.

**Comment by tonymorris** [comment]
boohoo, I don't like it when someone understands the subject matter that I do not. When they helpfully explain the subject to me, it's especially bad, because tears come out! I am going to call them names instead, and grab a tissue. That will definitely resolve this matter.

**Comment by proc0** [comment]
No  need to redefine promises, which are tailored to ease the pain of asynchronous coding with imperative style. There are plenty of JS functional libraries that expose the Future Monad, which is essentially a Promise in FP land. For example - https://github.com/fluture-js/Fluture  - or - https://github.com/mudge/pacta

**Comment by puffnfresh** [comment]
@proc0 asynchronous imperative coding can be done better than Promises/A+ - those libraries (and my original, 5 year old post) show how.

**Comment by Risto-Stevcev** [comment]
Wow this thread is pretty depressing...
This proposal has nothing to do with haskell or the haskell community. If you have a bad perception of either of those it really shouldn't affect how you feel about this proposal in any way

**Comment by dmitriz** [comment]
This example might be relevant to illustrate the danger of the current `Promise` implementation mixing `.map` and `.chain` behaviors into `.then`:
https://codepen.io/dmitriz/pen/rvNWxw?editors=0012
```js
let val = {
	then: x => x
}
let val1 = {
	then: x => x(1)
}
let val2 = {
	then: {x:1}
}

// Nothing is getting out of this promise
// with  the `.resolve` not actually resolving
Promise.resolve(val).then(result => {
	console.log("I am silently ignored!")
	console.log("Result is:", result);
})
.catch(e => {
	console.log("I am also silently ignored!")
	console.log(e)
})

Promise.resolve(val1).then(result => {
	console.log("Result1 is:", result);
})

Promise.resolve(val2).then(result => {
	console.log("Result2 is:", result);
})
```

It can be argued that the case in the first example is rare, but if it might occur unexpectedly, the code becomes hard to debug and generally unsafe.

Is there any reason not to provide the same `Promise` class with the safer `.map` and `.chain` methods in addition to the (looking more convenient but) potentially dangerous `.then`?
Or is any library doing this already?

**Comment by robotlolita** [comment]
@dmitriz we've discussed it extensively when ES6 was being discussed and the conclusion was: you can't have both (https://esdiscuss.org/topic/promise-cast-and-promise-resolve#content-40). They chose the non-monadic version of promises, and even though I still think that was a bad choice it's what we've got now.

You can just not use promises and write your own types, then build something like async/await on top of generators, and you'll get roughly the same characteristics Promises give you by default, but without the drawbacks (but also without the runtime optimisations).

**Comment by bergus** [comment]
> You can just not use promises and write your own types, then build something like async/await on top of generators

…or use an existing library that does just that, like [Creed](http://blog.briancavalier.com/creed/) :-)

**Comment by dmitriz** [comment]
@robotlolita 
Thank you very much for the link, an interesting read, when also frustrating for an outsider as everything refers to some context that is often to be found elsewhere or spread over multiple places. It is unfortunate that [people now erroneously say Promises are monads](https://medium.com/@dmitri145/actually-the-promises-were-not-made-into-monads-see-the-in-famous-discussion-in-1526891cde6e), where people looking for explanation seem to have hard time finding it concisely in one place.

I must admit my PhD degree in Maths still does not help me to extract from that @brendaneich comment nor the following comments debating these, a scientific rigorous proof that implementing `.then` on top of the more primitive `.map` and `.flatMap` (aka `.chain`) and exposing all of them on the `Promise` instance is fundamentally impossible. 

Is there a such proof written anywhere that is complete, objective and not opinion based?

That is, a proof that is impossible to have a `Promise` class having exactly the same methods as currently implemented, plus the `.map` and `.chain`. (As a matter of personal opinion, I find `.flatMap` more descriptive than `.chain` that has already been used in JS to mean other things.)

> You can just not use promises and write your own types, then build something like async/await on top of generators, and you'll get roughly the same characteristics Promises give you by default, but without the drawbacks (but also without the runtime optimisations).

Could you please explain the runtime optimisation? Wouldn't the native `.chain` be more performant (and `.map` even more), comparing to `.then` with all its plumbings?

**Comment by dmitriz** [comment]
@bergus 
> …or use an existing library that does just that, like Creed :-)

Thank you, this is what makes writing my comments worth is ;)

So if this library can implement all the methods simultaneously without breaking `.then`, doesn't it refute the arguments in  https://esdiscuss.org/topic/promise-cast-and-promise-resolve ?

**Comment by bergus** [comment]
@dmitriz 

> but also without the runtime optimisations

Actually that's wrong. Algebraic promises can be much better optimised than promises which need to do recursive flattening in every step.

> Doesn't it refute the arguments in https://esdiscuss.org/topic/promise-cast-and-promise-resolve?

That's a very long and very old thread, even using names that had changed their meaning since. Which argument in particular do you refer to?

Creed does not break `then`, but it does break interoperability. You only get Promise/A+ assimilation interoperability by using the "broken" `then` method, which cannot be fixed and maintain compatibility (at least about recursive assimilation). You can add the more primitive operations like `chain` and `of` and `map` to an A+ compatible library, but they will only work with promises from that particular library.

**Comment by robotlolita** [comment]
@dmitriz 
> a scientific rigorous proof that implementing .then on top of the more primitive .map and .flatMap (aka .chain) and exposing all of them on the Promise instance is fundamentally impossible.

It's possible to write that, and easy enough. The problem, really, is that it creates more room for confusing behaviour. People using `.then` expect promises to always be flattened, people using `.chain` expect promises to never be flattened. When you start using other people libraries, and those expectations combine in the code, you're most likely going to run into bugs that are hard to track because people had different expectations about how to go about writing the code.

The whole point of algebraic structures is to define a single way of composing structures such that you can always reason about their composition in a simpler way. If you start adding too many ways of composing values, that quickly falls apart, and you're left with none of the benefits.

**Comment by dmitriz** [comment]
@bergus 
>>  but also without the runtime optimisations

> Actually that's wrong. Algebraic promises can be much better optimised than promises which need to do recursive flattening in every step.

That was my thought too. Perhaps @robotlolita meant the unwrapping optimisation if you re-implement it on top of `.chain`. But you can also use the native `.then` if you have to.

> That's a very long and very old thread, even using names that had changed their meaning since. Which argument in particular do you refer to?

The argument that it is "fundamentally impossible to have both functionalities coexisting", e.g. here:
https://esdiscuss.org/topic/promise-cast-and-promise-resolve#content-40

> Creed does not break then, but it does break interoperability. You only get Promise/A+ assimilation interoperability by using the "broken" then method, which cannot be fixed and maintain compatibility (at least about recursive assimilation). You can add the more primitive operations like chain and of and map to an A+ compatible library, but they will only work with promises from that particular library.

The monadic `.chain` (or `.flatMap`) should expect function returning the same monad. Do you mean, passing the native promise inside the `.chain` is not recognized by `creed`? 

The `.map` and `.of` are simpler in that they merely wrap the value. So in what way should they work with other libraries?

@robotlolita 
> It's possible to write that, and easy enough. The problem, really, is that it creates more room for confusing behaviour. People using .then expect promises to always be flattened, people using .chain expect promises to never be flattened. When you start using other people libraries, and those expectations combine in the code, you're most likely going to run into bugs that are hard to track because people had different expectations about how to go about writing the code.

I don't quite understand how it is different from using any library `X` with two different methods `a` and `b`. Some folks will use `a` and get functionality of `a`, others will use `b`. Any compliant promise would have to provide both. The methods are called and work differently, yes. Confusion is of course always subjective and hard to debate for that reason, but is there any fundamental reason it would be impossible for the two methods to coexist?

> The whole point of algebraic structures is to define a single way of composing structures such that you can always reason about their composition in a simpler way. If you start adding too many ways of composing values, that quickly falls apart, and you're left with none of the benefits.

An algebraic structure is just a function with several arguments, satisfying certain properties. Even integers have two separate algebraic structures -- `+` and `*` that perfectly coexist with no confusion. 

Why there should be a single way to define it? I don't mean any personal preference here but a fundamentally possible way to satisfy different people's needs.

**Comment by dmitriz** [comment]
@bergus
I do not know if that addresses the interoperability concern,
but it seems `creed.chain` works as desired even with native promises:

```sh
> creed = require('creed')
> p = creed.resolve(1).chain(_ => Promise.resolve(2))
Promise { pending }
> p
Promise { fulfilled: 2 }
```

**Comment by bergus** [comment]
@dmitriz, I mean something like
```js
import creed from 'creed';
import other from 'some-other-algebraic-promise-lib';

const p = creed.resolve(other.of(other.of(1))); // similar, in creed.of(…).chain(_ => …)
p.map(console.log) // 1, or Other(1) ???
```
"Monadic" promises and "non-monadic" promises can *coexist*, yes, but they are incompatible with each other in terms of assimilation. One would need to spec a second algorithm (possibly even using `then`) that would not recursively unwrap.

**Comment by dmitriz** [comment]
@bergus I really can't see any problems.

If your `of` here conforms to [the Pointed Functor spec](https://stackoverflow.com/a/41816326/1614973), then `other.of(other.of(1))` should not unwrap like in `[[1]]`, so nothing happens.
Whereas if `resolve` is unrwapping, similar to `Promise.resolve`, then in your example it should unwrap twice down to `creed.resolve(1)`. (Apart from `resolve` being a suboptimal naming choice as `Promise.resolve` does not actually have to resolve if run over a promise.)

And the general principle should be simple too. You have the infinitely unwrapping `then` and `resolve` from any library, one-step-unwrapping `flatMap` and non-unwrapping `map` and `of` again, from any library. Any time there is a promise-conformant object from any library (or theneable), it should be unwrapped by the unwrapping methods. The infinitely unwrapping ones will continue until they can't unwrap anymore. That would actually simplify the current spec in half 😀   Am I missing something?

**Comment by bergus** [comment]
@dmitriz TBH, I can see that solution as well, and have long been a proponent of "monadic promises" and wanted to avoid recursive unwrapping from the get-go (in A+). I'm probably not the one who can argue well against this. Now we just have to convince the ES committee and the engine implementors that this is a good idea…

**Comment by dmitriz** [comment]
@bergus I have found another validation by @briancavalier that it is possible to implement `of` and `chain` without breaking `then`: https://github.com/promises-aplus/promises-spec/issues/97#issuecomment-16452068

That seems to be what `creed` is doing, where also wrapping Promises in Promises is possible via `of`.  Surprisingly, I have read people's comments opposing the mere possibility to have Promises wrapped into Promises. Apparently some older promise libraries were against it, again for unclear reasons. It just looks frustratingly obscure for such an important decision affecting so many people.

**Comment by emilypi** [comment]
It's like I'm watching a chronological replaying of all the fundamental mistakes "pragmatic" developers make in their attempts to avoid learning something new. Brilliant!

@puffnfresh  holy hell m8

**Comment by punmechanic** [comment]
This aged like milk. TypeScript is now becoming incredibly popular. Typed JavaScript was very fringe in 2013, but in 2019 it is the opposite and now we are stuck with the decisions made back in 2013 because someone didn't like typed languages.

That's unfortunate.

**Comment by dmitriz** [comment]
> @trinitroglycerin now we are stuck with the decisions made back in 2013 because someone didn't like typed languages.

Maybe @domenic has something to say about it?

**Comment by kennknowles** [comment]
I love every additional comment here so many years later. I never muted this thread. The best part is that I have a lifetime of it to look forward to, for two reasons:

1. The things done wrong here are fundamental to programming/computation itself, so there will never be a time when it is not wrong. And probably never be a time when it doesn't adversely effect programming in Javascript/Typescript.
2. Those who think the conclusions here are OK will never search it up. This thread is kept alive by those who encountered the wrongness and searched the web for what went wrong.

So for those arriving now and forever: Welcome. You are in good company.

**Comment by davidchambers** [comment]
Like @kennknowles, I have never muted this thread. It had not occurred to me, though, that commenting here could provide pedagogical value. I now see this possibility.

[Broken Promises][1]† documents the problematic characteristics of promises: eagerness, cancellation, specialized API, error handling, and mixing exceptions with failures.


† _Please excuse the Medium link._


[1]: https://medium.com/@avaq/broken-promises-2ae92780f33

**Comment by dmitriz** [comment]
https://www.reddit.com/r/programming/comments/ed7flb/functors_what_are_they/fbgjves/

> The original Github issue on whether promises should be monadic is one of the most horrific examples of ignorance and closed-mindedness I have ever seen. https://github.com/promises-aplus/promises-spec/issues/94

**Comment by friedbrice** [comment]
The specs are extended gutters and the gutters are full of mixed metaphors and when the weak metaphors finally break down, all the servers will crash. The accumulated filth of all their test suites and practical engineering will foam up about their waists and all the pragmatists and spec writers will look up and shout 'SAVE US!'...and I'll look down and whisper 'No.'

**Comment by AriaFallah** [comment]
Lmao @friedbrice instead of reviving an 8-year-old thread to live out your fantasies of not saving people from A+ promises, consider therapy

**Comment by friedbrice** [comment]
Joke's on _you_ @AriaFallah! I already do therapy! XD

**Comment by Abastro** [comment]
How dumb lol. There are regions and niches each programming langs have, and ppl are deliberately breaking it. Also all the circlejerking. Kudos for the manager who closed this issue, well managed the circumstances.

**Comment by beezee** [comment]
@Abastro yes very very dumb lolol. a sound mathematical model for **_*computation*_** is a "region and niche" for _some_ **_*computer*_** programming languages. what "regions and niches" belong to the **_*computer*_** programming languages that _don't_ care about a sound mathematical model for **_*computation*_**? landfills and early childhood education?

But I'm sure you are well versed in category theory and its application to programming, so your assessment is careful and well informed and not a knee-jerk anti-intellectual reaction to the scary idea that there's things you don't yet understand which might make you a better programmer.

**Comment by simpadjo** [comment]
@beezee please let's not start a rant. This thread looks much better as it is: an old discussion, yearly snarky comments and a stream of github issue references that proves the point :)

**Comment by Abastro** [comment]
@beezee For one thing, CT does not apply well in CS(tbh it is embarrassing so much that it became a meme among mathematicians). For another, there are several computation models not one. Each language and environment may choose one over another, and using incompatible models at once would easily lead to mess-up. Lol

**Comment by beezee** [comment]
@Abastro well you know what a monad is, I can't possibly imagine how you reason a Promise is not one, and just _what_ sound model of computation you think is at play in the promises spec. The rest of your comment is noise.

**Comment by Abastro** [comment]
@beezee Basically, in JS we unroll structures like arrays including Promise as well. This allows more succint API for common usecases. This property of JS violates Functor property for good. Presence of exception in imperative settings is another problem for monadic representation. Really, what benefit you ever get from these CT theoretical bureaucracy in JS, a dynamic imperative language?
Stop trying to equate languages.

**Comment by emilypi** [comment]
> This property of JS violates Functor property for good. 

Are you telling me `for`-loops are broken by unrolling? What exactly do you think a functor is? 

> Presence of exception in imperative settings is another problem for monadic representation.

In the presence of exceptions, Javascript isn't a language. Do you believe addition is a poor abstraction because it is broken in the presence of exceptions? List concatenation? Data declaration? The `new` keyword? No? Then accept the fact that some people attempt to make their world more reasonable by working within a reasonable model. Even with these defects, I'm sure that algebraic models are useful enough to be included in the language. So too can CT.

There is absolutely nothing wrong with applying a partial model for what modicum of  principled reasoning you can get in a fragment of the language that is reasonable to work with. Bringing CT to other languages has been wildly successful in many different ways, for many different types of languages, but it does not change your world just by existing. You can always opt in or opt out of using abstractions, but the general reasoning principles we use to guide our abstract reasoning can and *should* be sound, especially in situations like this. If you're balking at syntax, that's one thing, but don't sit there and tell me you're going to reject attempting to apply sound reasoning principles. 

> JS, a dynamic imperative language?

I've made a Monad crocheting a hat for a friend. I should *hope* JS can handle that level of complexity.

**Comment by tonymorris** [comment]
> @beezee Basically, in JS we unroll structures like arrays including Promise as well. This allows more succint API for common usecases. This property of JS violates Functor property for good. Presence of exception in imperative settings is another problem for monadic representation. Really, what benefit you ever get from these CT theoretical bureaucracy in JS, a dynamic imperative language?
> Stop trying to equate languages.



> CT does not apply well in CS(tbh it is embarrassing so much that it became a meme among mathematicians).

This is both incorrect, in terms of programming, but also misrepresents mathematicians. Happy to help you learn why, any time.

_yes, the ignoramus comments are getting old_

**Comment by beezee** [comment]
@emilypi i am anxiously awaiting a talk where you share the crocheting monad

**Comment by emilypi** [comment]
@beezee if you attended the talk on smash products, you would have seen me building riemannian manifolds out of paper and tape. This stuff can be either very big, or very smol. Even for the notoriously complex topos, you can build a very small one with three thumbtacks and some colored yarn (different colors, to differentiate arrows). Whether or not the arrangement means anything to you is in the quality of the observer, but a topos exists there in the thing nonetheless. 

Same with monads. To deny that a thing *is* a monad is to deny its intrinsic structure. It's like denying clouds exist. When we say "this is a monad", we're not saying "we can build this thing into a monad with lots of effort and force", we are simply observing how it acts under certain observable preconditions (like no exceptions!), and that translates semantically into literally 2 behaviors: lifting a value into the thing, and multiplying via composition (`m (m a) -> m a`). For that reason, I really dislike jargon-ey conversations like this. If we just said "hey, promise has a nicer minimalist interface consisting of `return` and `andThen` which have nicer reasoning principles than the existing interface", it wouldn't be controversial. But as soon as anyone says "monads", everyone loses their goddamn minds. It's reactive to the jargon, not the thing.

**Comment by beezee** [comment]
@emilypi I did catch that talk it was awesome. lol @ denying clouds exist, I love this take. Reminds me of one of my favorite Lambda Man moments where Phil Wadler talks about [invention vs discovery](https://www.youtube.com/watch?v=aeRVdYN6fE8&t=3134s)

**Comment by tonymorris** [comment]
> literally 2 behaviors

Is 2 a number and is it less than the number 3?

>  But as soon as anyone says "monads", everyone loses their goddamn minds. It's reactive to the jargon, not the thing.

In terms of pedagogy, I agree that there is a common and somewhat profoundly under-informed overreaction to the terminology "is a monad", which generally doesn't exist when we say that 2 is a "number", despite being just another observation of structure. I speculate that the reason for this is the practice of early education, where "number" becomes an obvious and accepted piece of jargon that we can all communicate successfully with each other.

I think there is a further push (frustration?), sometimes without success, to move the term "monad" (and other unfamiliar terminology) into a similar acceptance. Further, a tacit and optimistic suggestion of something like, "perhaps your mathematics education was halted at aged 9[^1], but never mind, just catch up, I'll help!"

I think this is why you see a less-forgiving use of jargon in what started out as, "this not a mathematics learning session -- but rather, discussion on a programming API intended for common use; don't screw it up!"

[^1]: [Lockhart's Lament](https://www.maa.org/external_archive/devlin/devlin_03_08.html)

**Comment by MostAwesomeDude** [comment]
I recently wrote [a small note](https://gist.github.com/MostAwesomeDude/76e61e6634571da296ec1fccc6784c19) explaining how, among other things, promises are not just monads, but "mothers of monads"; they identify codensity. As a result, it is not negotiable whether promises are monadic; it is only a choice of whether the language is ergonomic when handling monadic actions. While it is far too late for ECMAScript, perhaps other languages can benefit from hindsight.

**Comment by dmitriz** [comment]
@MostAwesomeDude Your note is discussing the codensity monad but doesn't seem to mention promises at all. Then in a comment below you say "let's imagine promises as a functor". I don't quite understand what you mean by "imagine", but just for a reference, here is my StackOverflow post proving mathematically that Promise is neither a functor nor a monad: https://stackoverflow.com/a/50173415/1614973

**Comment by MostAwesomeDude** [comment]
@dmitriz: My note is not language-specific. Indeed, JS/ES promises do not form a functor, but this is a language-specific design defect. For example, [Twisted Python's Deferreds](https://twistedmatrix.com/documents/current/core/howto/defer-intro.html) are well-known to form a functor and monad, including @Twisol's conception of bifunctorality. (The oldest example I could find of somebody who is not me saying this is [15 years ago](https://old.reddit.com/r/programming/comments/mjcf/the_monad_laws/cmobm/). (I suppose that this technically makes my post yet another instance of Twisted users pointing out issues with JS's event-loop design. (Sorry.)))

More pointedly, to understand where I ended up on all of this, note that [Monte promises](https://monte.readthedocs.io/en/latest/promises.html) form a monad, and although I didn't intend it at the time, it is exactly the codensity monad for Monte's event loop. I chose to be more like E and Twisted, and less like ECMAScript and Node.js.

To make the link explicit: callback-oriented asynchronous continuations are an example of a codensity monad, or "mother of all monads"; ergonomic expression of a codensity monad leads to ergonomic expression of many other monads too. This is what @puffnfresh is really driving at achieving, since there are typically only a few builtin codensity monads per programming language. However, there is more than one, which invokes the spectre of colored functions; hence my original note.

**Comment by dmitriz** [comment]
@MostAwesomeDude Yes, I was only referring to the JS promise spec - the subject of this repository. Thanks for showing other languages have better, more compliant implementations, demonstrating that it would have been totally possible to do it in JS, yet it wasn't done. What this shows through, every time you say the promise is a functor or monad, you need to qualify you are referring to other implementations, since JS one is not.

**Comment by Jerry1144** [comment]
Looking at this years old thread… I think maybe the problem is y'all failed to provide a concrete example for separating fmap and bind (ie map and flatMap) uses of Then()?

Earlier example argues that `SomePromise.then(a => Promise b),then(Promise b => c)` ought to be equivalent to `SomePromise.then(a => c)` because monad laws, or otherwise it's not DRY. Conservatives fails to see (and he failed to show, really, by using malformed `a => Promise b` and an `Thenable b => c` expecting that malformed promise/thenable) why ppl ever would like to `map` an `a => Promise b` onto a Promise at all. Breaking monad laws breaks this particular use case while keeping any sane uses intact, no?

So, `map`ing instead of `flatMap`ing an `a => Promise b` is only because of you later `map` `Promise b => a` onto the same thing, and monad laws guarantee you can just compute `a => c` instead. Years later do we have concrete examples for this now?

I'm a newbie, but `Promise b => c` looks terribly like signature for a Promise canceler, as this function appears to know beforehand what a given Promise would end up as, perhaps by looking at the constituents of the Promise. `map`'d into a PromiseArray it possibly immediately cancels other Promises and uses the return value of the first returning promise. Mapped into a Promise and maybe it cancels the whole promise chain up to the previous `.thenMap(a => Promise b)`? 

Monad laws also guarantee you can transform every `.then(a => c)` into `.thenMap(a => Promise b).thenMap(Promise b => c)`, but what use could such transformation possibly be? 

PS: FP tutorials always assert monad laws be upheld without giving convincing examples why anyone or the interpreter **need** those _certain good behavior_. If GHC were transforming some `fmap` into `fmap funcIntoSomeMonad . fmap SomeMonadCatamorphism` as an optimization magic it would be better to be pointed out.

**Comment by puffnfresh** [comment]
@Jerry1144 code reuse

**Comment by emilypi** [comment]
Kuromi for your thoughts

![signal-2021-12-25-110035](https://user-images.githubusercontent.com/10459342/168156888-5bf64dfb-a64a-43bf-8586-ea0f6adb8c93.gif)

**Comment by KSXGitHub** [comment]
JavaScript was shit because it was created in haste, yet it continues to be shit because the devs be stubborn for the sake of stubborn.

**Comment by malcolmocean** [comment]
lol in the world of async/await inside try/catch it sure feels like the point of promises "(modeling synchronous control flow from imperative languages)" as domenic puts it, is well achieved without having then take two arguments.  and way BETTER achieved in this way.
